### ISSUE TITLE
Company: Plashape

### ISSUE THREAD

**Issue by doriancrutcher** [veliovgroup/profiles#10]
- __GitHub Organization__: @doriancrutcher

Create Minecraft NFTs to empower minecraft artist!

---

*Want to work at Plashape?*
Checkout their [open positions](https://github.com/veliovgroup/jobs/labels/company%3Aplashape)

**Comment by dr-dimitru** [comment]
Hello @doriancrutcher ,

We had to the things around, all profiles are moved to the repo under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account at [obs.openweb.dev](https://jobs.openweb.dev/)
