### ISSUE TITLE
Company: MetaGuild

### ISSUE THREAD

**Issue by jlwaugh** [veliovgroup/profiles#11]
- __GitHub Organization__: @metaguild

guild about guilds

---

*Want to work at MetaGuild?*
Checkout their [open positions](https://github.com/veliovgroup/jobs/labels/company%3Ametaguild)

**Comment by dr-dimitru** [comment]
Hello @jlwaugh ,

We had to move things around, all profiles are moved to the repo under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account at [jobs.openweb.dev](https://jobs.openweb.dev/)
