### ISSUE TITLE
Company: Real Items

### ISSUE THREAD

**Issue by davidmd222** [veliovgroup/profiles#12]
- __GitHub Organization__: @RealItems

NFT's for the real world (anti-counterfeit, Product Serialization, Direct to Consumer Rewards)

---

*Want to work at Real Items?*
Checkout their [open positions](https://github.com/veliovgroup/jobs/labels/company%3Areal-items)

**Comment by dr-dimitru** [comment]
Hello @davidmd222 ,

We had to move things around, all profiles are moved to the repo under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account at [jobs.openweb.dev](https://jobs.openweb.dev/)
