### ISSUE TITLE
Company: Pixel8

### ISSUE THREAD

**Issue by ImTheCodeFarmer** [veliovgroup/profiles#13]
- __GitHub Organization__: `https://github.com/pixel8-llc`

New to the NEAR world but eagar to learn. We build applications to help automate the online world of business.

---

*Want to work at Pixel8?*
Checkout their [open positions](https://github.com/veliovgroup/jobs/labels/company%3Apixel8)

**Comment by dr-dimitru** [comment]
Hello @jhammond2012 ,

We had to move things around, all profiles are moved to the repo under NEAR namespace and there was no clear way to move issues. I'm sorry for the inconvenience, but you would need to create a new account at [obs.openweb.dev](https://jobs.openweb.dev/)
